version: '3.7'

services:
  node:
    container_name: tsgqlserver-node-container
    image: node:12.18.1-alpine
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      TZ: Asia/Tokyo
    volumes:
      - ./dist:/app
    working_dir: /app
    ports:
      - 3000:3000
    tty: true
